{
  "compute_environment": "LOCAL_MACHINE",
  "distributed_type": "NO",
  "main_process_port": 29512,
  "downcast_bf16": false,
  "machine_rank": 0,
  "gpu_ids": "0",
  "main_training_function": "main",
  "mixed_precision": "no",
  "num_machines": 1,
  "num_processes": 1,
  "rdzv_backend": "static",
  "same_network": true,
  "tpu_use_cluster": false,
  "tpu_use_sudo": false,
  "use_cpu": false
}
