
# Absolute paths for different resources
paths:
  train_file: "data/train.computed.24k.json"
  val_file: "data/val.json"
  test_file: "data/val.json"
  # resume_from_checkpoint: "/home/sang/work/TangoFlux/step_7000/step_7000"
  resume_from_checkpoint: ""
  output_dir: "outputs/"
  vae_dir: "/mnt/disks/training-data-refine/RAPCHAT_DATASET_VAE"

# Training-related parameters
training:
  per_device_batch_size: 12
  learning_rate: 5e-4
  gradient_accumulation_steps: 1
  num_train_epochs: 80
  num_warmup_steps: 200
  max_audio_duration: 30
  max_grad_norm: 0.7
  
 
# Model and optimizer parameters, 
model:
  num_layers: 6
  num_single_layers: 18
  in_channels: 64
  attention_head_dim: 128
  joint_attention_dim: 1024
  num_attention_heads: 8
  audio_seq_len: 645
  max_duration: 30
  uncondition: false
  text_encoder_name: "google/flan-t5-large"
  infilling: false
  




